const mockResponses = [
  { word: 'at', score: 5475, numSyllables: 1 },
  { word: 'caveat', score: 4418, numSyllables: 3 },
  { word: 'that', score: 3776, numSyllables: 1 },
  { word: 'hat', score: 3092, numSyllables: 1 },
  { word: 'rat', score: 2723, numSyllables: 1 },
  { word: 'bat', score: 2642, numSyllables: 1 },
  { word: 'flat', score: 2483, numSyllables: 1 },
  { word: 'mat', score: 1849, numSyllables: 1 },
  { word: 'fat', score: 1792, numSyllables: 1 },
  { word: 'chat', score: 1729, numSyllables: 1 },
  { word: 'pat', score: 1678, numSyllables: 1 },
  { word: 'scat', score: 1276, numSyllables: 1 },
  { word: 'format', score: 1223, numSyllables: 2 },
  { word: 'combat', score: 1206, numSyllables: 2 },
  { word: 'habitat', score: 1190, numSyllables: 3 },
  { word: 'spat', score: 1160, numSyllables: 1 },
  { word: 'tat', score: 1140, numSyllables: 1 },
  { word: 'brat', score: 1053, numSyllables: 1 },
  { word: 'matte', score: 1043, numSyllables: 1 },
  { word: 'stat', score: 988, numSyllables: 1 },
  { word: 'gnat', score: 910, numSyllables: 1 },
  { word: 'plutocrat', score: 900, numSyllables: 3 },
  { word: 'sat', score: 870, numSyllables: 1 },
  { word: 'vat', score: 815, numSyllables: 1 },
  { word: 'aristocrat', score: 812, numSyllables: 4 },
  { word: 'splat', score: 709, numSyllables: 1 },
  { word: 'matt', score: 701, numSyllables: 1 },
  { word: 'gat', score: 699, numSyllables: 1 },
  { word: 'slat', score: 682, numSyllables: 1 },
  { word: 'nat', score: 679, numSyllables: 1 },
  { word: 'autocrat', score: 663, numSyllables: 3 },
  { word: 'acrobat', score: 634, numSyllables: 3 },
  { word: 'ziggurat', score: 629, numSyllables: 3 },
  { word: 'polecat', score: 624, numSyllables: 2 },
  { word: 'thermostat', score: 608, numSyllables: 3 },
  { word: 'sprat', score: 599, numSyllables: 1 },
  { word: 'bobcat', score: 570, numSyllables: 2 },
  { word: 'laundromat', score: 564, numSyllables: 3 },
  { word: 'diplomat', score: 536, numSyllables: 3 },
  { word: 'copycat', score: 528, numSyllables: 3 },
  { word: 'chitchat', score: 527, numSyllables: 2 },
  { word: 'brickbat', score: 515, numSyllables: 2 },
  { word: 'democrat', score: 511, numSyllables: 3 },
  { word: 'muskrat', score: 507, numSyllables: 2 },
  { word: 'wildcat', score: 507, numSyllables: 2 },
  { word: 'bureaucrat', score: 462, numSyllables: 3 },
  { word: 'kat', score: 452, numSyllables: 1 },
  { word: 'batt', score: 449, numSyllables: 1 },
  { word: 'begat', score: 438, numSyllables: 2 },
  { word: 'doormat', score: 429, numSyllables: 2 },
  { word: 'wombat', score: 419, numSyllables: 2 },
  { word: 'dat', score: 392, numSyllables: 1 },
  { word: 'tomcat', score: 388, numSyllables: 2 },
  { word: 'aerostat', score: 385, numSyllables: 3 },
  { word: 'latke', score: 379, numSyllables: 1 },
  { word: 'look at', score: 331, numSyllables: 2 },
  { word: 'technocrat', score: 311, numSyllables: 3 },
  { word: 'strat', score: 288, numSyllables: 1 },
  { word: 'platte', score: 275, numSyllables: 1 },
  { word: 'sadat', score: 269, numSyllables: 2 },
  { word: 'thundercat', score: 262, numSyllables: 3 },
  { word: 'scrat', score: 259, numSyllables: 1 },
  { word: 'gatt', score: 252, numSyllables: 1 },
  { word: 'pussycat', score: 252, numSyllables: 3 },
  { word: 'schmatte', score: 216, numSyllables: 1 },
  { word: 'platt', score: 204, numSyllables: 1 },
  { word: 'scatt', score: 203, numSyllables: 1 },
  { word: 'tit-for-tat', score: 202, numSyllables: 3 },
  { word: 'pratt', score: 201, numSyllables: 1 },
  { word: 'pack rat', score: 186, numSyllables: 2 },
  { word: 'placemat', score: 176, numSyllables: 2 },
  { word: 'elat', score: 175, numSyllables: 2 },
  { word: 'in that', score: 175, numSyllables: 2 },
  { word: 'bratt', score: 172, numSyllables: 1 },
  { word: 'glatt', score: 168, numSyllables: 1 },
  { word: 'hard hat', score: 168, numSyllables: 2 },
  { word: 'tit for tat', score: 164, numSyllables: 3 },
  { word: 'top hat', score: 154, numSyllables: 2 },
  { word: 'such that', score: 152, numSyllables: 2 },
  { word: 'nonfat', score: 149, numSyllables: 2 },
  { word: 'pick at', score: 148, numSyllables: 2 },
  { word: 'butterfat', score: 144, numSyllables: 3 },
  { word: 'get at', score: 142, numSyllables: 2 },
  { word: 'cowboy hat', score: 139, numSyllables: 3 },
  { word: 'blatt', score: 137, numSyllables: 1 },
  { word: 'gujarat', score: 131, numSyllables: 3 },
  { word: 'patte', score: 124, numSyllables: 1 },
  { word: 'high hat', score: 120, numSyllables: 2 },
  { word: 'kitcat', score: 118, numSyllables: 2 },
  { word: 'arrive at', score: 107, numSyllables: 3 },
  { word: 'hatte', score: 106, numSyllables: 1 },
  { word: 'fall flat', score: 100, numSyllables: 2 },
  { word: 'inmarsat', score: 99, numSyllables: 3 },
  { word: 'babysat', score: 96, numSyllables: 3 },
  { word: 'gnaw at', score: 96, numSyllables: 2 },
  { word: 'stand pat', score: 94, numSyllables: 2 },
  { word: 'place mat', score: 93, numSyllables: 2 },
  { word: 'mexican hat', score: 91, numSyllables: 4 },
  { word: 'patt', score: 90, numSyllables: 1 },
  { word: 'catt', score: 89, numSyllables: 1 }
]

describe('datamuse api', () => {
  it.skip('should have a a test', () => {})
})
